// <auto-generated />
namespace SocialNet.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddLasrVisit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLasrVisit));
        
        string IMigrationMetadata.Id
        {
            get { return "201501281710096_AddLasrVisit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
