// <auto-generated />
namespace SocialNet.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPicture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPicture));
        
        string IMigrationMetadata.Id
        {
            get { return "201501032036130_AddPicture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
